### ISSUE TITLE
Add `name` field with case-insensitive matching?

### ISSUE THREAD

**Issue by cmutel** [fjuniorr/flowmapper#46]
It seems like name matching is case sensitive - is this really necessary? Maybe we can put case-insensitivity at the bottom of the list of functions to make sure it comes last?

**Comment by cmutel** [comment]
Probably not necessary but we might also do some unicode normalization as well.

**Comment by fjuniorr** [comment]
@cmutel although the matching should be case-insensitive the return values for `Flowmap.to_randonneur` and `Flowmap.to_glad` should be the original name for the target flows, correct? For the source flow I'm assuming this is the case per our discussion in https://github.com/fjuniorr/flowmapper/issues/27

For example, should I return:

```python
{
    "source": {
        "name": "1,4-Butanediol",
        "categories": ["Air", "(unspecified)"],
        "unit": "kg"
    },
    "target": {
        "uuid": "09db39be-d9a6-4fc3-8d25-1f80b23e9131",
        "name": "1,4-Butanediol", # upper case
        "context": "air/unspecified",
        "unit": "kg",
    },
    "conversion_factor": 1,
    "comment": "Identical names",
}
```

or:

```python
{
    "source": {
        "name": "1,4-Butanediol",
        "categories": ["Air", "(unspecified)"],
        "unit": "kg"
    },
    "target": {
        "uuid": "09db39be-d9a6-4fc3-8d25-1f80b23e9131",
        "name": "1,4-butanediol", # lower case
        "context": "air/unspecified",
        "unit": "kg",
    },
    "conversion_factor": 1,
    "comment": "Identical names",
}
```

In some sense I could ask the same question about `unit` when https://github.com/fjuniorr/flowmapper/issues/49 is done (eg. if the unit of the target flow was normalized, should I return the original or the normalized) and `context` (which we could convert to lowercase instead of [add case variations to `CONTEXT_MAPPING`](https://github.com/fjuniorr/flowmapper/blob/096552df90ff7dbccc7bd4d23413b8913e316b46/flowmapper/constants.py#L43) ).

My feeling is that we want (2) for all the properties. 

It might even be the case that for context we should return a list instead of `'/'.join` (except for `Flowmap.to_glad` which is a tabular representation).

**Comment by fjuniorr** [comment]
We [got 2 extra matches](https://github.com/fjuniorr/flowmapper-ci/commit/9304fd25abb6ca6860741621cdf0bb56cff01f8d) in `agribalyse-3.1.1-biosphere`:

- "Tau-fluvalinate" to "tau-Fluvalinate" (`92681c17-2514-4151-aabf-baee3fd8e5f5`)
- "Dipropylthiocarbamic acid S-ethyl ester" to `EPTC` (`fd950a9b-db9f-41c9-a8b0-d61f152f6ef2`) via the synonym "Dipropylthiocarbamic Acid S-Ethyl Ester"

I've used the new [`FlowProperty`](https://github.com/fjuniorr/flowmapper/blob/3791c194553e0186cd161c7fd254f8893004cc47/flowmapper/flowproperty.py) for [handling `Flow.name` and `Flow.synonyms`](https://github.com/fjuniorr/flowmapper/blob/3791c194553e0186cd161c7fd254f8893004cc47/flowmapper/flow.py#L33-L34).
